# Generated by Django 3.2.5 on 2021-07-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('price', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('UAN', 'UAN')], default='RUB', max_length=3)),
                ('info', models.CharField(help_text='short description', max_length=50)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
