# Generated by Django 3.2.5 on 2021-08-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unweb', '0002_auto_20210801_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(null=True),
        ),
    ]
